version: "3.7"

services:
  transaction-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=transaction
      - POSTGRES_USER=transaction
      - POSTGRES_PASSWORD=transaction
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - transaction-database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: